services:
  # --- NHÓM MONITORING ---
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki # Gắn thư mục máy thật vào thư mục /loki của container
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - smart-gplx-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3200:3000" # Truy cập Grafana qua localhost:3200
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - smart-gplx-network
    depends_on:
      - loki

  # --- NHÓM APPS ---
  # web:
  #   build: ./apps/web
  #   ports:
  #     - "3000:3000" # Frontend chạy cổng 3000
  #   networks:
  #     - smart-gplx-network

  # backend:
  #   build: ./apps/node-backend
  #   ports:
  #     - "3001:3000" # Backend chạy cổng 3001 (tránh trùng với Web)
  #   environment:
  #     - LOKI_HOST=http://loki:3100 # Gọi trực tiếp bằng tên dịch vụ "loki"
  #     - DATABASE_URL=mysql://user:pass@mysql:3306/smart_gplx_db # (Nếu có DB)
  #   networks:
  #     - smart-gplx-network
  #   depends_on:
  #     - loki

networks:
  smart-gplx-network:
    driver: bridge