version: '3.8'

services:
  # --- NHÓM MONITORING (GIÁM SÁT) ---
  loki:
    image: grafana/loki:latest
    container_name: smart_gplx_loki
    ports:
      - "3100:3100"
    volumes:
      - ./infra:/etc/loki/custom-config/
      - loki_data:/loki
    command: -config.file=/etc/loki/custom-config/loki-config.yaml
    networks:
      - smart-gplx-network

  prometheus:
    image: prom/prometheus:latest
    container_name: smart_gplx_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra:/etc/prometheus/custom-config/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/custom-config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=730d'
    networks:
      - smart-gplx-network

  grafana:
    image: grafana/grafana:latest
    container_name: smart_gplx_grafana
    ports:
      - "3200:3000" 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - smart-gplx-network
    depends_on:
      - loki
      - prometheus

  # --- NHÓM CACHE & DATABASE (CƠ SỞ DỮ LIỆU) ---
  redis-cache:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "root"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "root", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - smart-gplx-network

  mysql-db:
    image: mysql:8
    container_name: smart_gplx_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=smart_gplx_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smart-gplx-network

    # --- NHÓM NOSQL ---
  mongodb:
    image: mongo:latest
    container_name: smart_gplx_mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017" 
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username root --password password --authenticationDatabase admin --eval 'db.runCommand({ping:1})' || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - mongo_data:/data/db 
    networks:
      - smart-gplx-network

# --- KHAI BÁO MẠNG ---
networks:
  smart-gplx-network:
    driver: bridge

# --- KHAI BÁO KHỐI DỮ LIỆU (CHỖ BẠN BỊ THIẾU GÂY RA LỖI) ---
volumes:
  redis_data:
  mysql_data:
  loki_data:
  mongo_data:
  prometheus_data: